### ISSUE TITLE
Unable to find (or install) JSCustom on Package Control

### ISSUE THREAD

**Issue by tslaton** [Thom1729/Sublime-JS-Custom#124]
I can't seem to find JSCustom (also tried a few similar queries) on Package Control with Sublime Text 4.

I wonder if it is related to the `MISSING` badge over on the [Package Control page](https://packagecontrol.io/packages/JSCustom)?

OS: macOS 11.4
Sublime version: 4107

**Comment by Thom1729** [comment]
Thanks for the report. I'm looking into it.

**Comment by Thom1729** [comment]
Looking at the channel page, it lists the latest stable versions for ST3 and ST4, but it's showing an older tag for the prerelease. I released v4.1.0-beta.2 yesterday, so that's probably related. If the Package Control crawler couldn't get it for some reason, it might have marked the package missing. I think this still has to be manually reset, so I'll ping the appropriate parties.

**Comment by felixcatto** [comment]
Any news? It is sad to live without this package :)

**Comment by Thom1729** [comment]
Fixed. Please confirm/disconfirm.

The problem was an issue with the Package Control crawler that kept it from finding the ST3-compatible tags. I've worked around it by deleting some old dev tags.

**Comment by felixcatto** [comment]
Now all is working fine, thanks!

**Comment by kireerik** [comment]
Seems like it is missing again.
