### ISSUE TITLE
JSCustom breaks vue syntax highlighting

### ISSUE THREAD

**Issue by ellipticaldoor** [Thom1729/Sublime-JS-Custom#20]
![image](https://user-images.githubusercontent.com/3449006/36933376-ab9d750a-1ecf-11e8-9d81-6cff1319519a.png)

To reproduce this behaviour first you have to install the package Vue Syntax Highlight.

After installing JSCustom and restarting sublime text, vue components start to look like in the screenshot above.

Even if I uninstall JSCustom the highlight stays broken, I have to manually remove the folder:
```
~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/JS\ Custom
```

These errors are easy to see when using the official vue template https://github.com/vuejs-templates/webpack

**Comment by Thom1729** [comment]
@ellipticaldoor What version of Sublime and of Vue Syntax Highlight are you using?

This is (was) a [known issue](https://github.com/sublimehq/Packages/issues/1302) with the Vue package. [The way that it was importing the JavaScript syntax was incorrect](https://github.com/sublimehq/Packages/issues/1309), and when [the core JavaScript syntax was updated](https://github.com/sublimehq/Packages/pull/1009) the Vue syntax broke. The Vue syntax [has since been rewritten](https://github.com/vuejs/vue-syntax-highlight/pull/109) and should no longer suffer from the above issue. I have just tested this to confirm that the issue no longer exists.

However, the new Vue syntax uses the `embed`/`escape` feature introduced in [Sublime dev build 3153](https://forum.sublimetext.com/t/dev-build-3153/33014). (Using this feature simplifies the implementation and should substantially reduce both the in-memory size of the compiled syntax and the time it takes for Sublime to recompile the Vue syntax when an embedded syntax changes.) Unfortunately, this feature is not yet present in a stable build. It looks like you are using the old version of the Vue syntax, presumably on stable build 3143.

It is not possible to remedy the problem on the JavaScript end, because the internal implementation details that the old Vue syntax implicitly relied upon were [causing systematic bugs](https://github.com/sublimehq/Packages/issues/885) and [blocking new features](https://github.com/sublimehq/Packages/issues/324). The old Vue syntax works with babel-sublime because it suffers from those bugs.

There are two immediate workarounds. First, upgrading to dev build 3153 or later will give you the new, fixed Vue syntax. Second, using explicit semicolons in your JavaScript rather than relying on the automatic semicolon insertion algorithm will avoid the cases that babel-sublime and the old Vue syntax get wrong. (It seems that the official Vue template omits semicolons, which is generally considered poor practice but is actually advocated by some styles. Omitting semicolons while using babel-sublime is likely to trigger a number of subtle bugs.)

If a new stable build is released soon, the problem will go away altogether. Failing that, it may be possible to backport the new Vue syntax to work with stable build 3143.  I'll open up an issue over there and see if anyone is willing to do that.

**Comment by ellipticaldoor** [comment]
Awesome! It works just fine on latest sublime dev 3157

**Comment by ellipticaldoor** [comment]
It looks like the latest version on master has this problem
