### ISSUE TITLE
Improve commenting of JSX

### ISSUE THREAD

**Issue by ellipticaldoor** [Thom1729/Sublime-JS-Custom#21]
I detected some problems with jsx comments.

# Uncomment doesn't work
If I comment one line and then uncomment it, some curlybraces are being leaved behind.

before
![image](https://user-images.githubusercontent.com/3449006/36933728-24da956e-1ed6-11e8-8db5-f5daeb4511f9.png)
after
![image](https://user-images.githubusercontent.com/3449006/36933730-2c8c127e-1ed6-11e8-8971-ba8675346b8f.png)
should be
![image](https://user-images.githubusercontent.com/3449006/36933737-396aaa5a-1ed6-11e8-8078-57636b3da4ef.png)

# Indentation spaces shouldn't be included on the comment
before
![image](https://user-images.githubusercontent.com/3449006/36933776-cc5bfc1a-1ed6-11e8-9772-996462bd4490.png)
after
![image](https://user-images.githubusercontent.com/3449006/36933792-fbd9947a-1ed6-11e8-870b-fa86ac4bad11.png)
should be
![image](https://user-images.githubusercontent.com/3449006/36933801-0b9cab9a-1ed7-11e8-8be5-724b11f4d87c.png)

# Inner component is not commented if indentation spaces are not selected
If you select a component like in the next screenshot the comment shortcut doesn't work
![image](https://user-images.githubusercontent.com/3449006/36933818-40a4b9f4-1ed7-11e8-92f3-3cc8969903c4.png)

# Use normal javascript comments instead of jsx when the code is inside parenthesis ()
before
![image](https://user-images.githubusercontent.com/3449006/36933915-0f4f033a-1ed9-11e8-8cdf-040b77c6a548.png)
after
![image](https://user-images.githubusercontent.com/3449006/36933919-18be9110-1ed9-11e8-8d8f-0f5ecf7ab769.png)
should be
![image](https://user-images.githubusercontent.com/3449006/36933922-23998464-1ed9-11e8-90c8-c3e230a150a0.png)

# The javascript that Im using for this examples
``` javascript
function HelloWorld({
  greeting = "hello",
  greeted = '"World"',
  silent = false,
  onMouseOver
}) {
  if (!greeting) {
    return null;
  }

  // TODO: Don't use random in render
  let num = Math.floor(Math.random() * 1e7)
    .toString()
    .replace(/\.\d+/gi, "");

  return (
    <div
      className="HelloWorld"
      title={`You are visitor number ${num}`}
      onMouseOver={onMouseOver}
    >
      <strong>
        {greeting.slice(0, 1).toUpperCase() + greeting.slice(1).toLowerCase()}
      </strong>
      {greeting.endsWith(",") ? (
        " "
      ) : (
        <span style={{ color: "grey" }}>", "</span>
      )}
      <em>{greeted}</em>
      {silent ? "." : "!"}
    </div>
  );
}

```

**Comment by Thom1729** [comment]
This is an underlying bug with the core JavaScript syntax (which is probably my fault anyway). I've submitted a PR for the core syntax, and I've already applied the patch to JS Custom.

If the PR is not accepted in the next Sublime build, I may have to re-patch JS Custom, but I'm confident that the temporary discrepancy will be resolved soon.

**Comment by Thom1729** [comment]
…and in my haste to fix the bug, I've commented on the wrong bug.

**Comment by Thom1729** [comment]
I have updated the commenting behavior to match babel-sublime. (This is what it was supposed to be doing, but there were bugs.) However, this will not address all of the above concerns.

The central problem is that JSX does not support comments. There is no JSX comment syntax at all, and it is unlikely that one will be added. In order to fake it, we use a double-wrapping approach, but that approach has fundamental flaws. In particular, it is impossible for this system to round-trip correctly in the general case. Consider these lines:

```jsx
<div>
    {foo}
    foo
</div>
```

If you comment out the first `{foo}`, you'll get `{/*foo*/}`. If you comment out the second, you'll get — the same thing? The alternative is transforming the bare JSX text to a string (`{/*"foo"*/}`, but this is extremely problematic because JSX text behaves differently from JavaScript strings. The translation would be very complicated. And, of course, then commenting `foo` would produce the same result as commenting `{"foo"}`. In any case, it would be impossible to reliably reverse the operation by uncommenting, because multiple pre-commented constructs would be mapped onto the same commented construct.

One way to make it work would be to use a special labelled commenting syntax just for JSX text. For example, JSX text `foo` would transform to `{/*JSXText:foo*/}`. This could be reliably reversed. But it's an awful, ugly hack, and it does not play nicely with standard JavaScript comments. We'd have to find a transformation that could not possibly collide with real JavaScript, and that's getting harder to guarantee as new JavaScript features are designed. We'd also have to escape JSX text that contains `*/`. It might nevertheless be made to work somehow.

One specific problem that could perhaps be improved is removing the curly brackets when uncommenting. But this runs into round-trip issues as well. Consider the commented `{/*foo*/}`. Before the commenting, was this `foo` or `{foo}`? Whether or not we strip the brackets, there's a good chance we get it wrong. There is one special case in which we could make it work: if the contents inside `{/* */}` are a single JSX element, then we can safely strip the brackets when uncommenting, and this would probably be a reasonable thing to do under most circumstances.

It's questionable whether the built-in commenting system (inherited from TextMate) can handle something much more complicated than the current system. I've experimented with a system that would hook in to and selectively override the built-in mechanism, but it never reached a favorable usefulness-to-hackiness ratio. There might be a reasonable middle ground using JS Custom's more detailed scoping, but there's an [issue with selector scoring](https://github.com/SublimeTextIssues/Core/issues/2152) that would probably interfere with the nesting typical of JSX code.

I am open to any suggestions you may have. I'm sure that we can improve on babel-sublime's commenting functionality. For now (as of the 1.0.10 release), it should at least *match* babel-sublime in this regard.

**Comment by Thom1729** [comment]
(See also https://github.com/babel/babel-sublime/issues/262)

**Comment by ellipticaldoor** [comment]
I don't have enough skill to understand how everything works so at the moment I think I can't help to solve this.

**Comment by ellipticaldoor** [comment]
Looks Like vscode handle jsx comments very good, maybe it can be useful for some inspiration.

**Comment by Thom1729** [comment]
It does seem to do a good job overall, though there are some bugs. Integrating it into Sublime's commenting system might be tricky, but I'll look into it.

**Comment by Riseley** [comment]
Will this be of any use?

https://programmingliftoff.com/enable-jsx-commenting-sublime-text-3/

**Comment by duranivan** [comment]
Also, this package might help as a temporary solution ([here](https://github.com/mcissel/React-Comments-Sublime-Text)).. It is working for me so far...

**Comment by Thom1729** [comment]
JSX commenting should be significantly improved in v4 for ST4.
