### ISSUE TITLE
Consider to use Ecmascript as the base

### ISSUE THREAD

**Issue by dangh** [Thom1729/Sublime-JS-Custom#4]
[bathos/Ecmascript-Sublime](https://github.com/bathos/Ecmascript-Sublime) is the best syntax highlighting right now. It already supports React and ES stage-3 features. The only missing part is Flow syntax. It would be great if we can patch it to support Flow.

Here's a quick comparison, Ecmascript (below) support ES6 decorator, and it can detect syntax error.
![screen shot 2018-01-18 at 3 59 24 am](https://user-images.githubusercontent.com/1020347/35064337-a38f0b8c-fc04-11e7-870a-692495343b7b.png)

**Comment by Thom1729** [comment]
Full ECMAScript support is a top priority. While some features are currently absent from the core JavaScript syntax, I am [actively working](https://github.com/sublimehq/Packages/issues/1269) to add them and I hope that we may see 100% Stage-3 support in the next stable release. In the mean time, I may apply some of the outstanding patches to this syntax in anticipation of their eventual inclusion in core.

If there are specific features that are a high priority for you, I can probably put them next on the list.

Ecmascript-Sublime is an impressive piece of work, and in many ways it inspired the work that I've done on the core JavaScript syntax. However, it has several key disadvantages:

- It's 5,447 lines of code, making it challenging to modify or debug.
- It is much slower than the core syntax or JS Custom. Last time I checked, Ecmascript-Sublime took several times as long as core to highlight files.
- It uses its own unique build system, which would not integrate well with JS Custom.
- It differs from the core syntax in scoping and behavior, which means that tools designed for the core syntax are likely not to work with Ecmascript-Sublime.

In addition, I personally find its strict parsing to be a hindrance rather than a help. The core syntax is designed to handle syntax errors gracefully while you're typing. To catch errors, no syntax definition can replace a good linter.

For these reasons, I intend to stay with the core syntax. However, because of the modular nature of JS Custom, this shouldn't be a limiting factor. If another JavaScript package does something differently from the core syntax, it's probably possible to add an extension that provides the new behavior.
