### ISSUE TITLE
Build syntax fails

### ISSUE THREAD

**Issue by toberndo** [Thom1729/Sublime-JS-Custom#48]
With JSCustom v1.0.23 and Sublime Text 3.1.1, Build 3176 on macOS 10.14.1 I get the following error:
```
File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1036, in run_
    return self.run()
File "/Users/toberndo/Library/Application Support/Sublime Text 3/Installed Packages/JSCustom.sublime-package/build_js_custom_syntaxes.py", line 105, in run
TypeError: build() missing 1 required positional argument: 'error_highlighter'
```

**Comment by Thom1729** [comment]
It looks like I forgot to actually release a tag for a change in the `yaml_macros_engine` dependency. I've done that now. The channel should update in an hour or so, and when your local copy of the dependency is updated the bug should be resolved.

**Comment by toberndo** [comment]
Works for me now. Thanks!

Another issue I found is that when I uninstall JSCustom with "Remove Package" in Package Control, then Sublime Text hangs and I need to use task manager to shut it down. Not sure if that is more an issue of Sublime Text, but I tried to uninstall other packages without running into this issue.

**Comment by Thom1729** [comment]
FYI, the first issue is due to Package Control not adding dependencies to `sys.path` when they're installed. I used to have code in here to manually add them, but I think I removed it because it's an awful kludge. I guess I should probably put it back.

Not aware of the removal issue. The next major release should clean up the internals, and I'll be sure to test that scenario.
