### ISSUE TITLE
JS Custom last update break syntax highlighing

### ISSUE THREAD

**Issue by LoiKos** [Thom1729/Sublime-JS-Custom#83]
Hi, 
i upgrade JSCustom to the latest version 2.3.1 this morning and i face an issue with syntax highlighting

I get all my jsx to get no highlight : 
![image](https://user-images.githubusercontent.com/9548473/71816020-9bbd2480-3081-11ea-9e05-45043b491599.png)

and i get it back when i comment the section with`||` operator  
![image](https://user-images.githubusercontent.com/9548473/71816095-cf984a00-3081-11ea-8e30-db41c9f2090b.png)

I have no idea where it come from but i get this on all my files. ( For example i have a switch case  where only the first case is highlight)

Have you any idea where does it come from ?

**Comment by Thom1729** [comment]
I can take a detailed look at this in a couple hours. In the meantime, it would be very helpful if you could:

1. Rebuild syntaxes and see if the problem goes away.
2. Post the contents of your JS Custom preferences file, and the name of the configuration that you're using.
3. Post the code that's being mis-highlighted as text so that I can copy-paste it directly.

Whatever's going wrong is getting by the tests. If I can't fix it right away I'll revert to the previous release.

**Comment by mcissel** [comment]
This started today for me, too. It's happening when I have `string_object_keys: true`

**Comment by LoiKos** [comment]
1. Try to re-build syntax doesn't change anything
2. My JS Custom preferences file : 
```
{
    "configurations": {
        "Default": {},
        "React": {
            "file_extensions": [ "js", "jsx" ],
            "flow_types": false,
            "jsx": true,
            "string_object_keys":true,
        }
    },

}
```
3. i'll give you an example file as soon as possible

**Comment by LoiKos** [comment]
as @mcissel said it seems to happened only when `string_object_keys: true`

**Comment by LoiKos** [comment]
i have created a simple file that reproduce the problem i face : 

import React, { useState, useMemo } from 'react'

function Test({ fetch, create, retrieve }) {
  const [value] = useState(10)

  const { isLoading, isSuccess, isError } = useMemo(() => {
    if (fetch === 'Loading' || create === 'Loading' || retrieve === 'Loading') {
      return { isLoading: true, isSuccess: false, isError: false }
    } else if (fetch === 'Success' || create === 'Success') {
      return { isLoading: false, isSuccess: true, isError: false }
    } else if (fetch === 'Error' || create === 'Error') {
      return { isLoading: false, isSuccess: false, isError: true }
    }
    return { isLoading: false, isSuccess: false, isError: false }
  }, [retrieve, fetch, create])

  // const { isLoading, isSuccess, isError } = () => {
  //   switch (fetch) {
  //     case 'Loading':
  //       return { isLoading: true, isSuccess: false, isError: false }
  //     case 'Error':
  //       return { isLoading: false, isSuccess: false, isError: true }
  //     case 'Success':
  //       return { isLoading: false, isSuccess: true, isError: false }
  //     default:
  //       return { isLoading: false, isSuccess: false, isError: false }
  //   }
  // }

  return isLoading ? (
    <div> loading </div>
  ) : isSuccess ? (
    <div> {value} </div>
  ) : isError ? (
    <div> error </div>
  ) : null
}

export { Test }

You can use either `switch case` or `useMemo` you should be able to reproduce a problem with highlight

**Comment by Thom1729** [comment]
v2.3.2 is out, and it should fix this. Upstream changes to object literals broke the `string_object_keys` extension, and the tests didn't catch it because… there aren't any tests for `string_object_keys`. I'll write some for the next release.

Please reopen the issue and post a comment if the problem recurs in v2.3.2.

Thanks everyone for the prompt reports and for identifying `string_object_keys` as the culprit — it would have been a lot harder to track down otherwise, especially because I don't use `string_object_keys` myself.
